version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streams-api
    volumes: 
      - ".:/app"
    ports:
      - "0.0.0.0:5001:5000"
    tty: true